services:
  app:
    build: .
    container_name: agpk1-task-app
    restart: always
    env_file:
      - .env
    ports:
      - "5001:5000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production

  redis:
    image: redis:alpine
    container_name: agpk1-task-redis
    restart: always
